"""try array column in venue model

Revision ID: 013a14a971ca
Revises: 18ac8085e113
Create Date: 2020-12-22 20:05:21.531992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013a14a971ca'
down_revision = '18ac8085e113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
