"""add genres to Artrist model as array

Revision ID: a07bac4f5498
Revises: 013a14a971ca
Create Date: 2020-12-23 00:10:14.723847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07bac4f5498'
down_revision = '013a14a971ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genress', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genress')
    # ### end Alembic commands ###
